/**
 * Tests for genetics raw-data detection/summary (Phase 10). Covers 23andMe
 * and AncestryDNA header shapes, build-assembly extraction from comments,
 * and that an unrelated tab-separated file isn't claimed.
 *
 * NOTE: fixtures mirror the documented/well-known export layouts; update
 * fixtures + the parser together if a real export differs.
 */

import { describe, expect, it } from 'vitest'
import { detectGenotypeProvider, parseGenotypeSummary } from './genetics'

const TWENTYTHREEANDME = `# This data file generated by 23andMe at: Mon Jan 12 00:00:00 2026
# This file contains raw genotype data, including data that is
# not used in any 23andMe reports.
# Reference human assembly build 37.
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t72017\tAA
rs4970383\t1\t723798\tCC
rs3131972\t2\t752721\tAG
`

const ANCESTRYDNA = `#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 2026-01-12
#Data was collected using AncestryDNA array version: OmniExpressPlus
#Genetic data is reported with reference to human genome build 37 (GRCh37)
rsid\tchromosome\tposition\tallele1\tallele2
rs4477212\t1\t72017\tA\tA
rs3131972\t2\t752721\tA\tG
`

const UNRELATED_TSV = `id\tname\tvalue
1\tsteps\t8432
`

describe('detectGenotypeProvider', () => {
  it('recognizes a 23andMe raw-data export by its header row', () => {
    expect(detectGenotypeProvider(TWENTYTHREEANDME)).toBe('23andme')
  })

  it('recognizes an AncestryDNA raw-data export by its header row', () => {
    expect(detectGenotypeProvider(ANCESTRYDNA)).toBe('ancestrydna')
  })

  it('does not claim an unrelated tab-separated file', () => {
    expect(detectGenotypeProvider(UNRELATED_TSV)).toBeNull()
  })
})

describe('parseGenotypeSummary', () => {
  it('summarizes a 23andMe file: SNP count, chromosomes, build — never genotype calls', () => {
    const summary = parseGenotypeSummary(TWENTYTHREEANDME, '23andme')
    expect(summary).toEqual({
      provider: '23andme',
      snpCount: 3,
      chromosomes: ['1', '2'],
      buildAssembly: 'Build 37'
    })
    expect(JSON.stringify(summary)).not.toContain('AA')
  })

  it('summarizes an AncestryDNA file and extracts a GRCh-style build label', () => {
    const summary = parseGenotypeSummary(ANCESTRYDNA, 'ancestrydna')
    expect(summary).toEqual({
      provider: 'ancestrydna',
      snpCount: 2,
      chromosomes: ['1', '2'],
      buildAssembly: 'GRCh37'
    })
  })
})
